/**
  ******************************************************************************
  * &file    NVIC.H
  * &author  CC
  * &version V1.0.0
  * &date    2018-02-11
  * &brief   This file as a example.
  ******************************************************************************
  * &attention
  *
	* None
  *
  ******************************************************************************
  */
#ifndef _NVIC_H_
#define _NVIC_H_

#include "stm32f10x.h"

#endif /*_NVIC_H_*/





void NVIC_Config(uint8_t NVIC_IRQChannel,uint8_t PreemptionPriority,uint8_t SubPriority);









/********************* BY CC *************END OF FILE**************************/

